function [ R, Ra ] = PD_resp( wavel )
% function [ R, Ra ] = PD_resp( wavel )
% Provides responsivity curve for photodetector (currently, Hamamatsu
% S7478).
%
% Inputs
% wavel - desired wavelengths (nm)
%
% Outputs
% R - Responsivity (A/W)
% Ra - responsivity times area (A.cm^2/W). Multiply this value by
% irradiance (W/cm^2/nm) to get photocurrent generated by each wavelength.
% Integrate over wavelengths (e.g., trapz) to get total photocurrent.
%
% P. Silveira, March 2015
% BSX Proprietary

% temp = csvread('C:\Users\paulobsx\Google Drive\Tech_RD\Sensor\Development\Release to Market Product\PD_characterization\S7478_Responsivity.csv',3);
% wavel_nom = temp(:,1);
% R_nom = temp(:,2);

A = .25;   % PD area (5mmx5mm) for S7478 (in cm^2)

% Values read from plot shown on http://www.hamamatsu.com/us/en/product/category/3100/4001/4103/S7478/index.html
wavel_nom = [261.15
400
600
800
900
959
1000
1030
1100
1125.95
];

R_nom = [0
0.169
0.4
0.616
0.7
0.744
0.705
0.6
0.2
0
];


R = interp1(wavel_nom, R_nom, wavel, 'pchip', 0);
Ra = R*A;

end

